# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ertert',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/ertert',
                'lib_path': 'ertert'},
  'syms': { 'ertert.core': { 'ertert.core.foo': ( 'https://sky1ove.github.io/core.html#foo',
                                                  'https://github.com/sky1ove/ertert/blob/master/ertert/core.py#L7')}}}